apiVersion: apps/v1
kind: Deployment
metadata:
  name: build-complete-updater
spec:
 replicas: 1
 selector:
   matchLabels:
     app: {{ .Release.Name }}
 template:
   metadata:
     labels:
       app: {{ .Release.Name }}
   spec:
          serviceAccountName: {{ .Release.Name }}
          automountServiceAccountToken: true
          containers:
          - image: {{ .Values.imageNotifyCompletion }}
            name: notify-completion
            imagePullPolicy: IfNotPresent
            securityContext:
              runAsUser: 1000
              runAsGroup: 1000
            resources:
              limits:
                cpu: 1
                memory: 512Mi
            env:
              - name: NAMESPACE
                value: {{ .Release.Namespace }}
              - name: BROKER_URL
                value: {{ .Values.pubgrade_URL }}
