apiVersion: v1
kind: Service
metadata:
  name: mongodb-{{ .Release.Name }}
  labels:
    app: db
spec:
  ports:
  - port: 27017
    protocol: TCP
    name: mongodb
  selector:
    app: db
  type: ClusterIP
